//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace figYureD
{
    using System;
    using System.Collections.Generic;
    
    public partial class FigurineImage
    {
        public string Id { get; set; }
        public string FigurineId { get; set; }
        public string PictureUrl { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Figurine Figurine { get; set; }
    }
}
